/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  safelist: [
    // Animations
    'animate-fade-in-up',
    'animate-fade-in-up-delayed',
    'animate-float',
    'animate-pulse-glow',
    'animate-bounce-slow',
    'animate-sprinkle-fall',
    'animate-cupcake-bounce',
    'animate-icing-swirl',
    'animate-float-random',
    'animate-bounce-gentle',
    'animate-gradient-shift',
    'animate-gradient-text',
    'animate-spin-slow',
    'animate-pulse-fast',
    // Colors
    'cupcake-pink',
    'cupcake-coral',
    'cupcake-peach',
    'cupcake-cream',
    'cupcake-cherry',
    'cupcake-vanilla',
    'sprinkle-yellow',
    'sprinkle-blue',
    'sprinkle-green',
    'sprinkle-purple',
    'sprinkle-orange',
    // Text shadows and effects
    'text-shadow-sm',
    'text-shadow-md',
    'text-shadow-lg',
    'drop-shadow-lg',
    'drop-shadow-md',
    'drop-shadow-2xl',
    'gradient-text',
    'cupcake-text',
    'hover-lift',
    'shadow-3xl',
    'shimmer',
    'btn-primary',
    'btn-secondary',
    'focus-ring',
    'hero-text',
    'line-clamp-2',
    'line-clamp-3',
    // Fonts
    'font-quicksand',
    'font-poppins',
    'font-nunito',
    // Backdrop blur
    'backdrop-blur-xs'
  ],
  theme: {
    extend: {
      fontFamily: {
        'quicksand': ['Quicksand', 'sans-serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'nunito': ['Nunito', 'sans-serif'],
      },
      colors: {
        cupcake: {
          pink: '#FFB6C1',
          coral: '#FF7F7F',
          peach: '#FFCBA4',
          cream: '#FFF8DC',
          cherry: '#FF69B4',
          vanilla: '#F5F5DC',
        },
        sprinkle: {
          yellow: '#FFD700',
          blue: '#87CEEB',
          green: '#98FB98',
          purple: '#DDA0DD',
          orange: '#FFA500',
        },
        coral: {
          50: '#fef7f0',
          100: '#fdeee0',
          200: '#fad9c1',
          300: '#f6be97',
          400: '#f19a6b',
          500: '#ed7c47',
          600: '#de6330',
          700: '#b84d26',
          800: '#933f25',
          900: '#763522',
        },
        sunshine: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        rose: {
          50: '#fff1f2',
          100: '#ffe4e6',
          200: '#fecdd3',
          300: '#fda4af',
          400: '#fb7185',
          500: '#f43f5e',
          600: '#e11d48',
          700: '#be123c',
          800: '#9f1239',
          900: '#881337',
        },
        pink: {
          50: '#fdf2f8',
          100: '#fce7f3',
          200: '#fbcfe8',
          300: '#f9a8d4',
          400: '#f472b6',
          500: '#ec4899',
          600: '#db2777',
          700: '#be185d',
          800: '#9d174d',
          900: '#831843',
        }
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.8s ease-out forwards',
        'float': 'float 3s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'bounce-slow': 'bounce 2s infinite',
        'sprinkle-fall': 'sprinkle-fall 8s linear infinite',
        'cupcake-bounce': 'cupcake-bounce 3s ease-in-out infinite',
        'icing-swirl': 'icing-swirl 10s linear infinite',
        'fade-in-up-delayed': 'fade-in-up-delayed 1.5s ease-out forwards',
        'float-random': 'float-random 6s ease-in-out infinite',
        'bounce-gentle': 'bounce-gentle 2s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 8s ease infinite',
        'gradient-text': 'gradient-text 3s ease infinite',
        'spin-slow': 'spin-slow 20s linear infinite',
        'pulse-fast': 'pulse-fast 1s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'float-random': {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px) rotate(0deg) scale(1)' },
          '25%': { transform: 'translateY(-15px) translateX(10px) rotate(90deg) scale(1.1)' },
          '50%': { transform: 'translateY(-5px) translateX(-5px) rotate(180deg) scale(0.9)' },
          '75%': { transform: 'translateY(-20px) translateX(15px) rotate(270deg) scale(1.05)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '1', boxShadow: '0 0 5px rgba(255, 107, 157, 0.5)' },
          '50%': { opacity: '0.8', boxShadow: '0 0 20px rgba(255, 107, 157, 0.8)' },
        },
        'fade-in-up': {
          'from': { opacity: '0', transform: 'translateY(30px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-down': {
          'from': { opacity: '0', transform: 'translateY(-20px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        'bounce-gentle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'bounce-slow': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        'gradient-shift': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'gradient-text': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'spin-slow': {
          'from': { transform: 'rotate(0deg)' },
          'to': { transform: 'rotate(360deg)' },
        },
        'cupcake-bounce': {
          '0%, 100%': { transform: 'translateY(0px) scale(1)' },
          '50%': { transform: 'translateY(-20px) scale(1.05)' },
        },
        'icing-swirl': {
          '0%': { transform: 'rotate(0deg) scale(1)' },
          '50%': { transform: 'rotate(180deg) scale(1.1)' },
          '100%': { transform: 'rotate(360deg) scale(1)' },
        },
        'sprinkle-fall': {
          '0%': { transform: 'translateY(-100vh) rotate(0deg)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translateY(100vh) rotate(360deg)', opacity: '0' },
        },
        'pulse-fast': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.3' },
        },
      },
      textShadow: {
        'sm': '0 1px 2px rgba(0, 0, 0, 0.1)',
        'md': '0 2px 4px rgba(0, 0, 0, 0.1)',
        'lg': '0 4px 8px rgba(0, 0, 0, 0.1)',
      },
      dropShadow: {
        'sm': '0 1px 2px rgba(0, 0, 0, 0.1)',
        'md': '0 2px 4px rgba(0, 0, 0, 0.1)',
        'lg': '0 4px 8px rgba(0, 0, 0, 0.1)',
      },
      backdropBlur: {
        xs: '2px',
      },
      spacing: {
        '18': '4.5rem',
        '72': '18rem',
        '84': '21rem',
        '96': '24rem',
      },
    },
  },
  plugins: [
    require('tailwindcss-textshadow')
  ],
}
