/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  safelist: [
    'animate-float',
    'animate-float-random',
    'animate-pulse-glow',
    'animate-fade-in-up',
    'animate-fade-in-down',
    'animate-fade-in-up-delayed',
    'animate-bounce-gentle',
    'animate-bounce-slow',
    'animate-gradient-shift',
    'animate-gradient-text',
    'animate-spin-slow',
    'animate-cupcake-bounce',
    'animate-icing-swirl',
    'animate-sprinkle-fall',
    'animate-pulse-fast',
    'animate-pulse-subtle',
    'cupcake-coral',
    'cupcake-cherry',
    'cupcake-pink',
    'sunshine-400',
    'sunshine-500',
    'sunshine-600',
    'text-shadow-sm',
    'text-shadow-md',
    'text-shadow-lg',
    'drop-shadow-lg',
    'drop-shadow-md',
    'drop-shadow-2xl',
    'gradient-text',
    'cupcake-text',
    'hover-lift',
    'shadow-3xl',
    'shimmer',
    'btn-primary',
    'btn-secondary',
    'focus-ring',
    'hero-text',
    'line-clamp-2',
    'line-clamp-3',
    'font-quicksand',
    'font-poppins',
    'font-nunito'
  ],
  theme: {
    extend: {
      fontFamily: {
        'quicksand': ['Quicksand', 'sans-serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'nunito': ['Nunito', 'sans-serif'],
      },
      colors: {
        'cupcake-coral': '#FF6B9D',
        'cupcake-cherry': '#FF8FA3',
        'cupcake-pink': '#FFB3C6',
        'sunshine-400': '#FFD700',
        'sunshine-500': '#FFA500',
        'sunshine-600': '#FF8C00',
      },
      animation: {
        'float': 'float 3s ease-in-out infinite',
        'float-random': 'float-random 6s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'fade-in-up': 'fade-in-up 0.8s ease-out forwards',
        'fade-in-down': 'fade-in-down 0.3s ease-out forwards',
        'bounce-gentle': 'bounce-gentle 2s ease-in-out infinite',
        'bounce-slow': 'bounce-slow 3s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 8s ease infinite',
        'gradient-text': 'gradient-text 3s ease infinite',
        'spin-slow': 'spin-slow 20s linear infinite',
        'cupcake-bounce': 'cupcake-bounce 3s ease-in-out infinite',
        'icing-swirl': 'icing-swirl 10s linear infinite',
        'sprinkle-fall': 'sprinkle-fall 8s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'float-random': {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px) rotate(0deg) scale(1)' },
          '25%': { transform: 'translateY(-15px) translateX(10px) rotate(90deg) scale(1.1)' },
          '50%': { transform: 'translateY(-5px) translateX(-5px) rotate(180deg) scale(0.9)' },
          '75%': { transform: 'translateY(-20px) translateX(15px) rotate(270deg) scale(1.05)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '1', boxShadow: '0 0 5px rgba(255, 107, 157, 0.5)' },
          '50%': { opacity: '0.8', boxShadow: '0 0 20px rgba(255, 107, 157, 0.8)' },
        },
        'fade-in-up': {
          'from': { opacity: '0', transform: 'translateY(30px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-down': {
          'from': { opacity: '0', transform: 'translateY(-20px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        'bounce-gentle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'bounce-slow': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        'gradient-shift': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'gradient-text': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'spin-slow': {
          'from': { transform: 'rotate(0deg)' },
          'to': { transform: 'rotate(360deg)' },
        },
        'cupcake-bounce': {
          '0%, 100%': { transform: 'translateY(0px) scale(1)' },
          '50%': { transform: 'translateY(-20px) scale(1.05)' },
        },
        'icing-swirl': {
          '0%': { transform: 'rotate(0deg) scale(1)' },
          '50%': { transform: 'rotate(180deg) scale(1.1)' },
          '100%': { transform: 'rotate(360deg) scale(1)' },
        },
        'sprinkle-fall': {
          '0%': { transform: 'translateY(-100vh) rotate(0deg)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translateY(100vh) rotate(360deg)', opacity: '0' },
        },
      },
      textShadow: {
        'sm': '0 1px 2px rgba(0, 0, 0, 0.1)',
        'md': '0 2px 4px rgba(0, 0, 0, 0.1)',
        'lg': '0 4px 8px rgba(0, 0, 0, 0.1)',
      },
      dropShadow: {
        'sm': '0 1px 2px rgba(0, 0, 0, 0.1)',
        'md': '0 2px 4px rgba(0, 0, 0, 0.1)',
        'lg': '0 4px 8px rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [
    require('tailwindcss-textshadow')
  ],
}
